import type { BlogArticle, CatalogImage, Collection, CollectionSummary, Metafield, Product, ProductVariant } from "./types";
export interface ShopifyImageRaw { url: string; altText?: string | null; width?: number; height?: number }
interface ShopifyVariantRaw { id: string; title: string; sku?: string | null; availableForSale: boolean; price: { amount: string; currencyCode: string }; compareAtPrice?: { amount: string; currencyCode: string } | null }
export interface ShopifyProductRaw { id: string; handle: string; title: string; description: string; descriptionHtml: string; productType?: string; vendor?: string; tags?: string[]; featuredImage?: ShopifyImageRaw | null; images?: { nodes?: ShopifyImageRaw[] }; variants?: { nodes?: ShopifyVariantRaw[] }; collections?: { nodes?: Array<{ handle: string; title: string }> }; metafields?: Array<Metafield | null>; seo?: { title?: string | null; description?: string | null } }
export interface ShopifyCollectionRaw { id: string; handle: string; title: string; description: string; seo?: { title?: string | null; description?: string | null }; products: { nodes?: ShopifyProductRaw[]; pageInfo?: { hasNextPage: boolean; endCursor?: string | null } } }
export interface ShopifyCollectionSummaryRaw { id: string; handle: string; title: string; description?: string | null; image?: ShopifyImageRaw | null; seo?: { title?: string | null; description?: string | null } }
export interface ShopifyArticleRaw { id: string; handle: string; title: string; excerpt?: string | null; contentHtml?: string | null; publishedAt: string; tags?: string[]; image?: ShopifyImageRaw | null; authorV2?: { name?: string | null } | null; seo?: { title?: string | null; description?: string | null } }
function image(raw: ShopifyImageRaw): CatalogImage { return { url: raw.url, altText: raw.altText ?? "", width: raw.width, height: raw.height }; }
function variant(raw: ShopifyVariantRaw): ProductVariant { return { id: raw.id, title: raw.title, sku: raw.sku ?? undefined, availableForSale: raw.availableForSale, price: raw.price, compareAtPrice: raw.compareAtPrice ?? undefined }; }
export function normalizeProduct(raw: ShopifyProductRaw): Product { return { id: raw.id, handle: raw.handle, title: raw.title, description: raw.description ?? "", descriptionHtml: raw.descriptionHtml ?? "", featuredImage: raw.featuredImage ? image(raw.featuredImage) : undefined, images: (raw.images?.nodes ?? []).map(image), variants: (raw.variants?.nodes ?? []).map(variant), productType: raw.productType || undefined, vendor: raw.vendor || undefined, tags: raw.tags ?? [], collections: raw.collections?.nodes ?? [], metafields: (raw.metafields ?? []).filter((field): field is Metafield => Boolean(field?.value)), seo: { title: raw.seo?.title ?? undefined, description: raw.seo?.description ?? undefined } }; }
export function normalizeCollection(raw: ShopifyCollectionRaw): Collection { return { id: raw.id, handle: raw.handle, title: raw.title, description: raw.description ?? "", seo: { title: raw.seo?.title ?? undefined, description: raw.seo?.description ?? undefined }, products: (raw.products.nodes ?? []).map(normalizeProduct), pageInfo: { hasNextPage: raw.products.pageInfo?.hasNextPage ?? false, endCursor: raw.products.pageInfo?.endCursor ?? undefined } }; }
export function normalizeCollectionSummary(raw: ShopifyCollectionSummaryRaw): CollectionSummary { return { id: raw.id, handle: raw.handle, title: raw.title, description: raw.description ?? "", image: raw.image ? image(raw.image) : undefined, seo: { title: raw.seo?.title ?? undefined, description: raw.seo?.description ?? undefined } }; }
export function normalizeArticle(raw: ShopifyArticleRaw, blog: { handle: string; title: string }): BlogArticle { return { id: raw.id, handle: raw.handle, blogHandle: blog.handle, blogTitle: blog.title, title: raw.title, excerpt: raw.excerpt ?? "", contentHtml: raw.contentHtml ?? "", publishedAt: raw.publishedAt, image: raw.image ? image(raw.image) : undefined, author: raw.authorV2?.name ?? undefined, tags: raw.tags ?? [], seo: { title: raw.seo?.title ?? undefined, description: raw.seo?.description ?? undefined } }; }
